---
events:

  craft-conferencee-2021:
    label: "CraftHub online workshops"
    dates:
      - ticket-name-contains: "Falco"
        date: "November 11, 18, 25, 2020"
      - ticket-name-contains: "Rainsberger"
        date: "November 10, 12, 17, 19, 2020"
      - ticket-name-contains: "Titkos"
        date: "November 11, 18, 25, 2020"
    catering:
      - ticket-name-contains: "online"
        net-price: 0
    invoice:
      id-prefix: "WSH"
      logo-image: ""
      comment: |
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
      currency: USD
    email:
      replyToAddress: "hello@crafthub.events"
      subject: "Your invoice for your CraftHub online workshop"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for CraftHub's online workshop.

        Please find attached our official invoice for the workshop.
        In case you have an issue with the invoice, or you have a general question
        regarding the workshop please write to: hello@crafthub.events

        The CraftHub team

    bank:
      name: 'K&H Bank, SWIFT: OKHBHUHB'
      accountNumber: 'HU05-1040-3404-5052-6976-5752-1028'
    tito-signature-validator-env: TITO_TOKEN_ONLINE_WSH


  craft-online-conference:
    label: "CraftHub - Craft Conference 2021"
    dates:
      - ticket-name-contains: "Conference"
        date: "June 2-4, 2021"
      - ticket-name-contains: "Pinal"
        date: "February 24, 25, 2021"
      - ticket-name-contains: "Rising"
        date: "February 24, March 03, 10, 2021"
    catering:
      - ticket-name-contains: "Conference"
        net-price: 0
      - ticket-name-contains: "Workshop"
        net-price: 0
    invoice:
      id-prefix: "CRAFT"
      logo-image: ""
      comment: |
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
      currency: EUR
    email:
      replyToAddress: "hello@crafthub.events"
      subject: "Your invoice for your Craft Online Conference"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for Craft Online Conference.

        Please find attached our official invoice for the event.
        In case you have an issue with the invoice, or you have a general question
        please write to: hello@crafthub.events

        The CraftHub team

    bank:
      name: 'K&H Bank, SWIFT: OKHBHUHB'
      accountNumber: 'HU76-1040-3404-5052-6976-5752-1011'
    tito-signature-validator-env: TITO_TOKEN_CRAFT21
