---
events:

  craft-conferencee-2021:
    label: "CraftHub online workshops"
    dates:
      - ticket-name-contains: "ML/DL"
        date: "December 2 & 9, 2020"
      - ticket-name-contains: "MLflow"
        date: "November 23 & 24, 2020"
      - ticket-name-contains: "*"
        date: "March 3–5, 2021"
    catering:
      - ticket-name-contains: "*"
        net-price: 0
    invoice:
      id-prefix: "WSH"
      logo-image: ""
      comment: |
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
      currency: USD
    email:
      replyToAddress: "hello@crafthub.events"
      subject: "Your invoice for your CraftHub online workshop"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for CraftHub's online workshop.

        Please find attached our official invoice for the workshop.
        In case you have an issue with the invoice, or you have a general question
        regarding the workshop please write to: hello@crafthub.events

        The CraftHub team

    bank:
      name: 'K&H Bank, SWIFT: OKHBHUHB'
      accountNumber: 'HU05-1040-3404-5052-6976-5752-1028'
    tito-signature-validator-env: TITO_TOKEN_ONLINE_WSH

  craft-online-conference:
    label: "CraftHub - Craft Conference 2021"
    dates:
      - ticket-name-contains: "Conference"
        date: "June 2-4, 2021"
      - ticket-name-contains: "May 27-28"
        date: "May 27-28, 2021"
      - ticket-name-contains: "May 31-June 1"
        date: "May 31-June 1, 2021"
      - ticket-name-contains: "Combo"
        date: "May 27-June 4, 2021"
      - ticket-name-contains: "Patrick Kua"
        date: "May 28, 2021"
      - ticket-name-contains: "Katja"
        date: "May 28, 2021"
      - ticket-name-contains: "May 4-6"
        date: "May 4-6, 2021"
      - ticket-name-contains: "Wierckx"
        date: "June 15, 17, 2021"
    catering:
      - ticket-name-contains: "*"
        net-price: 0
    invoice:
      id-prefix: "CRAFT"
      logo-image: ""
      comment: |
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
      currency: EUR
    email:
      replyToAddress: "hello@crafthub.events"
      subject: "Your invoice for your Craft Online Conference"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for Craft Online Conference.

        Please find attached our official invoice for the event.
        In case you have an issue with the invoice, or you have a general question
        please write to: hello@crafthub.events

        The CraftHub team

    bank:
      name: 'Wise, BIC: TRWIBEB1XXX'
      accountNumber: 'BE34 9671 8845 4390'
    tito-signature-validator-env: TITO_TOKEN_CRAFT21

  amuse-workshops:
    label: "Amuse online workshops"
    dates:
      - ticket-name-contains: "Aarron"
        date: "April 28-29, 2021"
    catering:
      - ticket-name-contains: "*"
        net-price: 0
    invoice:
      id-prefix: "AMUSE"
      logo-image: ""
      comment: |
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
      currency: EUR
    email:
      replyToAddress: "hello@crafthub.events"
      subject: "Your invoice for your Amuse online workshop"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for our Amuse online workshop.

        Please find attached our official invoice for the event.
        In case you have an issue with the invoice, or you have a general question
        please write to: hello@crafthub.events

        The CraftHub team

    bank:
      name: 'Wise, BIC: TRWIBEB1XXX'
      accountNumber: 'BE34 9671 8845 4390'
    tito-signature-validator-env: TITO_TOKEN_AMUSEWSH21
    
  impact-conference-2021:
    label: "Impact Conference 2021"
    dates:
      - ticket-name-contains: "Impact"
        date: "October 4, 2021"
    catering:
      - ticket-name-contains: "test"
        net-price: 1
      - ticket-name-contains: "early"
        net-price: 31
      - ticket-name-contains: "regular"
        net-price: 31
      - ticket-name-contains: "group"
        net-price: 31
      - ticket-name-contains: "[OFFLINE] Impact equality"
        net-price: 62
      - ticket-name-contains: "ONLINE"
        net-price: 0
    invoice:
      id-prefix: "IMPCT"
      logo-image: ""
      comment: |
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
      currency: EUR
    email:
      replyToAddress: "hello@impact-conf.com"
      subject: "Your invoice for Impact Conference"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for Impact Conference.

        Please find attached our official invoice for the event.
        In case you have an issue with the invoice, or you have a general question
        please write to: hello@impact-conf.com

        The CraftHub team

    bank:
      name: 'Wise, BIC: TRWIBEB1XXX'
      accountNumber: 'BE34 9671 8845 4390'
    tito-signature-validator-env: TITO_TOKEN_IMPACT21
    
  amuse-conference-2021:
    label: "Amuse Conference 2021"
    dates:
      - ticket-name-contains: "October 5-6"
        date: "October 5-6, 2021"
    catering:
      - ticket-name-contains: "test"
        net-price: 1
      - ticket-name-contains: "early"
        net-price: 62
      - ticket-name-contains: "regular"
        net-price: 62
      - ticket-name-contains: "group"
        net-price: 62
      - ticket-name-contains: "[OFFLINE] Amuse equality"
        net-price: 124
      - ticket-name-contains: "ONLINE"
        net-price: 0
    invoice:
      id-prefix: "AMUSE"
      logo-image: ""
      comment: |
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
      currency: EUR
    email:
      replyToAddress: "hello@amuseconf.com"
      subject: "Your invoice for Amuse Conference"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for Amuse Conference.

        Please find attached our official invoice for the event.
        In case you have an issue with the invoice, or you have a general question
        please write to: hello@amuseconf.com

        The CraftHub team

    bank:
      name: 'Wise, BIC: TRWIBEB1XXX'
      accountNumber: 'BE34 9671 8845 4390'
    tito-signature-validator-env: TITO_TOKEN_AMUSE21
    
  crunch-conference-2021:
    label: "Crunch Conference 2021"
    dates:
      - ticket-name-contains: "October 7-8"
        date: "October 7-8, 2021"
    catering:
      - ticket-name-contains: "test"
        net-price: 1
      - ticket-name-contains: "early"
        net-price: 62
      - ticket-name-contains: "regular"
        net-price: 62
      - ticket-name-contains: "group"
        net-price: 62
      - ticket-name-contains: "[OFFLINE] Crunch equality"
        net-price: 124
      - ticket-name-contains: "ONLINE"
        net-price: 0
    invoice:
      id-prefix: "CRNCH"
      logo-image: ""
      comment: |
        Paid in full.
        This document was issued electronically and is therefore valid without signature.
      e-invoice: true
      currency: EUR
    email:
      replyToAddress: "hello@crunchconf.com"
      subject: "Your invoice for Crunch Conference"
      message: |
        Dear Attendee!

        Thank you for purchasing tickets for Crunch Conference.

        Please find attached our official invoice for the event.
        In case you have an issue with the invoice, or you have a general question
        please write to: hello@crunchconf.com

        The CraftHub team

    bank:
      name: 'Wise, BIC: TRWIBEB1XXX'
      accountNumber: 'BE34 9671 8845 4390'
    tito-signature-validator-env: TITO_TOKEN_CRUNCH21
